<a href="https://colab.research.google.com/github/vavan137/Yandex-Cup-2024/blob/main/F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd

df = pd.read_excel('/content/F transactions.xlsx')
df_2 = pd.read_excel('/content/F merchants.xlsx')

In [26]:
df = df[['cost','countertype','date','fraudbits','merchantid','model_cost']]
df = df.merge(df_2,how='left',on = 'merchantid')
df = df[df.fraudbits==0]
df.head(1)

,cost,countertype,date,fraudbits,merchantid,model_cost,coef,guild
0,7.39,buy,924-09-27 12:57,0,100299578,30.0,0.46,Гильдия Парфюмеров

Нужны расчетные поля: Амнистия и Час (операции)

In [33]:
df['amnesty'] = abs(df['model_cost']-df['cost'])/df['coef']
df['hour']= df['date'].str[10:12]
df.head(1)

,cost,countertype,date,fraudbits,merchantid,model_cost,coef,guild,amnesty,hour
0,7.39,buy,924-09-27 12:57,0,100299578,30.0,0.46,Гильдия Парфюмеров,49.152174,12

In [51]:
g_1 = df.groupby('guild')['amnesty'].mean()
g_2 = df[df['countertype']=='buy'].groupby('guild')['date'].count()
g_3 = df[df['countertype']=='sell'].groupby('guild')['date'].count()
#g_2
res = pd.concat([g_1,g_2,g_3],axis =1,keys =['av_amnesty','buy','sell'])
res['eff'] = res['sell']/res['buy']*res['av_amnesty']

In [55]:
row = res[res['eff']==res['eff'].max()]
row

                    av_amnesty   buy  sell         eff
guild
Братство Кузнецов  1835.734533  6161   659  196.355958

Час максимальной продуктивности по продажам

In [66]:
res2 = df[(df['guild']=='Братство Кузнецов') & (df['countertype']=='sell')].groupby('hour').size()
idx = res2.nlargest(1).index
res2.loc[idx]

hour
21    48
dtype: int64